FROM mariadb:latest

# Set environment variables for the root password and database creation
ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_DATABASE=
ENV MYSQL_USER=
ENV MYSQL_PASSWORD=

# Copy your initialization script to the right directory
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Expose the default port for MariaDB
EXPOSE 3306
